specVersion: "0.0.1"
description: ""
repository: "https://github.com/subquery/subql-starter"

schema: "./schema.graphql"

network:
  genesisHash: '0xa9d0b01b4eda83e41246b375a2a759e32124ff1496ef55b831e6dd8b797d1caa'
  endpoint: wss://cn3.dev.ad3.app:8443

dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleDidAssigned
          kind: substrate/EventHandler
          filter: #Filter is optional
            module: did
            method: Register
        - handler: handleCall
          kind: substrate/CallHandler




