specVersion: 0.2.0
name: starter-0_2_0
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
  endpoint: wss://polkadot.api.onfinality.io/public-ws
dataSources:
  - kind: substrate/Jsonfy
    startBlock: 1
    processor:
      file: ./jsonfy.js
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/JsonfyEvent
          filter:
            module: balances
            method: Deposit
